import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/components/ConvexClientProvider";
import { ClerkProvider } from "@clerk/nextjs";
import OnboardingGuard from "@/components/OnboardingGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

/**
 * Application root layout that renders the HTML skeleton and wraps page content with global providers and guards.
 *
 * The layout applies the Geist Sans and Geist Mono font variables and the `antialiased` body class, and nests
 * children inside ClerkProvider, ConvexClientProvider, and OnboardingGuard in that order.
 *
 * @param children - The page content to render inside the providers and guard.
 * @returns The root HTML layout element containing the configured providers and the provided children.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider dynamic>
          <ConvexClientProvider>
            <OnboardingGuard>{children}</OnboardingGuard>
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}